packageExtensions:
  "@hyperlane-xyz/widgets@*":
    dependencies:
      "@hyperlane-xyz/registry": "^20.0.0"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
