/** @type {import('tailwindcss').Config} */

const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontFamily: {
      sans: ['var(--font-family-sans)'],
      serif: ['var(--font-family-serif)'],
      mono: ['var(--font-family-mono)'],
      plex: ['var(--font-family-plex)'],
    },
    screens: {
      xs: 'var(--breakpoint-xs)',
      ...defaultTheme.screens,
    },
    extend: {
      colors: {
        black: 'var(--color-primary-black)',
        black2: '#15171a',
        white: 'var(--color-primary-white)',
        gray: {
          ...defaultTheme.colors.gray, 
          150: 'var(--color-gray-150)', 
          250: 'var(--color-gray-250)', 
          350: 'var(--color-gray-350)'
        },
        blue: {
          50: 'var(--color-blue-50)',
          100: 'var(--color-blue-100)',
          200: 'var(--color-blue-200)',
          300: 'var(--color-blue-300)',
          400: 'var(--color-blue-400)',
          500: 'var(--color-blue-500)',
          600: 'var(--color-blue-600)',
          700: 'var(--color-blue-700)',
          800: 'var(--color-blue-800)',
          900: 'var(--color-blue-900)',
        },
        red: {
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
        },
        green: {
          50: 'var(--color-green-50)',
          100: 'var(--color-green-100)',
          200: 'var(--color-green-200)',
          300: 'var(--color-green-300)',
          400: 'var(--color-green-400)',
          500: 'var(--color-green-500)',
          600: 'var(--color-green-600)',
          700: 'var(--color-green-700)',
          800: 'var(--color-green-800)',
          900: 'var(--color-green-900)',
        },
        pink: {
          50: 'var(--color-pink-50)',
          100: 'var(--color-pink-100)',
          200: 'var(--color-pink-200)',
          300: 'var(--color-pink-300)',
          400: 'var(--color-pink-400)',
          500: 'var(--color-pink-500)',
          600: 'var(--color-pink-600)',
          700: 'var(--color-pink-700)',
          800: 'var(--color-pink-800)',
          900: 'var(--color-pink-900)',
        },
        // Neutron mint/teal
        mint: {
          50: 'var(--color-mint-50)',
          100: 'var(--color-mint-100)',
          200: 'var(--color-mint-200)',
          300: 'var(--color-mint-300)',
          400: 'var(--color-mint-400)',
          500: 'var(--color-mint-500)',
          600: 'var(--color-mint-600)',
          700: 'var(--color-mint-700)',
          800: 'var(--color-mint-800)'
        },
        border: 'var(--color-border)',
        'border-hover': 'var(--color-border-hover)',
        arrow: 'var(--color-arrow)',
        'bg-button-main-disabled': 'var(--color-bg-button-main-disabled)',
        'bg-button-hover': 'var(--color-bg-button-hover)',
      },
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'sm2': '13px',
        '14px': '14px',
        'base': 'var(--font-size-base)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        '6xl': 'var(--font-size-6xl)',
        'balance': 'var(--font-size-balance)',
      },
      spacing: {
        88: 'var(--spacing-88)',
        100: 'var(--spacing-100)',
        112: 'var(--spacing-112)',
        128: 'var(--spacing-128)',
        144: 'var(--spacing-144)',
      },
      fontWeight: {
        regular: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        bold: 'var(--font-weight-bold)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-default)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        card: '5px',
        full: 'var(--radius-full)',
        modal: '5px',
      },
      blur: {
        xs: 'var(--blur-xs)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite;',
      },
      transitionProperty: {
        'height': 'height, max-height',
        'spacing': 'margin, padding',
      },
      maxWidth: {
        'xl-1': 'var(--max-width-xl-1)',
      },
      backgroundColor: {
        'button': 'var(--color-button)',
        'button-active': 'var(--color-button-active)',
        'button-hover': 'var(--color-button-hover)',
        'form': 'var(--color-card)',
        'sideBar': 'var(--color-sidebar)',
        'hoverForm': 'var(--color-hover-form)',
        'toast': 'var(--color-toast)',
        'disabled': 'var(--color-disabled)',
      },
      textColor: {
        primary: 'var(--color-text-primary)',
        secondary: 'var(--color-text-secondary)',
        error: 'var(--color-text-error)',
        disabled: 'var(--color-text-disabled)'
      },
      boxShadow: {
        dropdown: 'var(--shadow-dropdown)',
      },
    },
  },
  plugins: [],
};
